spring:
  redis:
    # 单机
    host: localhost
    port: 6379
    # 集群
#    cluster:
#      nodes: 10.19.185.11:6014,10.19.185.12:6014,10.19.185.13:6014
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    database: 14