spring:
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: localhost:8848
        namespace: c2897240-442e-4e0e-be5a-eef34d65341d
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-tyy-${spring.profiles.active}.yml

feign:
  sentinel:
    enabled: true
